# conda env create -f environment.yml
# conda env update -f environment.yml
# conda env remove -n clearmap-viz
# conda activate clearmap-viz
name: clearmap-viz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - graph-tool
  - pandoc
  - cython<3
  - natsort
  - matplotlib
  - seaborn
  - scikit-image
  - scikit-learn
  - pandas
  - tifffile
  - tqdm
  - pip:
    - napari[all]
    - itkwasm-morphological-contour-interpolation
